---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: routers
  tasks:

    - name: Get config for IOS Facts from devices
      ios_facts:
        gather_subset: all
      register: output  

    - name: Display the config
      debug: var=output
